/*******************************************************************************
 *                                                                             *
 * This font definition file is generated by FontGen v2.50 - Latin Grayscale   *
 *              by Bahri Okuroglu - fontgen@dreamsware.info                    *
 *                                  http://dreamsware.info                     *
 *                                                                             *
 * Make sure it is legal to use installed fonts on your PC for this conversion *
 *                                                                             *
 * Font definition for Tahoma 14                                               *
 *          bold: y                                                            *
 *          italic: n                                                          *
 *          underline: n                                                       *
 *          strikeout: n                                                       *
 *          direction: 0                                                       *
 *          compact vertical: n                                                *
 *          compact horizontal: y                                              *
 *          flip X: n                                                          *
 *          flip Y: n                                                          *
 *          1-bit grayscale (color=~pixel>>7)                                  *
 *          Current code page: windows-1252: ANSI Latin 1; Western European (Windows) *
 *                                                                             *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS' *
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,       *
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR      *
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR          *
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,       *
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,         *
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; *
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,    *
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR     *
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF      *
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE                                   *
 *******************************************************************************/


#include "fontgen.h"



extern const FONT_DEF Tahoma_14_n_bnnn_0_nh;

